[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "instagram-follower-audit"
version = "0.1.0"
description = "Instagram Follower Audit Tool"
requires-python = ">=3.8" 